ALTER TABLE dim_data        DISABLE ROW LEVEL SECURITY;
ALTER TABLE dim_cliente     DISABLE ROW LEVEL SECURITY;
ALTER TABLE dim_produto     DISABLE ROW LEVEL SECURITY;
ALTER TABLE dim_vendedor    DISABLE ROW LEVEL SECURITY;
ALTER TABLE dim_pagamento   DISABLE ROW LEVEL SECURITY;
ALTER TABLE dim_avaliacao   DISABLE ROW LEVEL SECURITY;
ALTER TABLE dim_localizacao DISABLE ROW LEVEL SECURITY;
ALTER TABLE fato_pedido_item DISABLE ROW LEVEL SECURITY;
